config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :friends
  resources :users do
    resources :tweets do
      put :like, on: :member
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_friendship
  validates :login, presence: true, uniqueness: true, format: { without: /.*admin.*/i }
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :find_tweet, except: [:index, :create]

  def index
    @tweets = model.all.order(created_at: :desc)
  end

  def create
    @tweet = model.new(tweet_params)
    @tweet.save
    redirect_to root_path
  end

  def edit
  end

  def update
    @tweet.update_attributes(tweet_params)
    redirect_to root_path
  end

  def destroy
    @tweet.destroy
    redirect_to root_path
  end

  def like
    unless @tweet.get_likes.exists?(voter: current_user)
      @tweet.liked_by current_user
    else
      @tweet.unliked_by current_user
    end
    render json: {status: 'success', likes_count: @tweet.get_likes.count}
  end

  private

  def find_tweet
    @tweet = model.find(params[:id])
  end

  def model
    current_user.tweets
  end

  def tweet_params
    params.require(:tweet).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
  def friends_for_user
    friends = current_user.friends
    render 'layouts/friend_list', friends: friends
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.haml
.alert.alert-dismissable{class: klass}
  %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', type: 'button'} ×
  = notice

app/views/layouts/_friend_list.haml
.row
  .col-lg-3.col-lg-offset-9
    .panel.panel-default
      .panel-heading
        %i.fa.fa-th-list.fa-fw
        Friends List
      .panel-body
        .list-group
          %a.list-group-item{:href => "#"}
            %i.fa.fa-user.fa-fw
            - friends.each do |x|
              = x.login
              %span.pull-right.text-muted.small
                %em
                - if x.current_sign_in_at
                  = time_ago_in_words(x.current_sign_in_at)
                  ago
        = link_to 'View All Friends', friends_path, class: 'btn btn-default btn-block'
        = link_to 'Find More Friends', friends_path, class: 'btn btn-default btn-block'

app/views/layouts/_header.haml
%nav.navbar.navbar-default.navbar-static-top{role: 'navigation', style: 'margin-bottom: 0'}
  .navbar-header
    %button.navbar-toggle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse', type: 'button'}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to 'Twitter', root_path, class: 'navbar-brand'
  %ul.nav.navbar-top-links.navbar-right
    - if user_signed_in?
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-user.fa-fw
          %i.fa.fa-caret-down
        %ul.dropdown-menu.dropdown-user
          %li
            = link_to edit_user_registration_path do
              %i.fa.fa-user.fa-fw
              User Profile
          %li.divider
          %li
            = link_to destroy_user_session_path, method: :delete do
              %i.fa.fa-sign-out.fa-fw
              Logout

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Twitter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .wrapper
      = render 'layouts/header'
      .row
        .navbar-default.sidebar{:role => "navigation"}
          .sidebar-nav.navbar-collapse.panel
            %ul#side-menu.nav.in
              %li
                %a.active{:href => "index.html"}
                  %i.fa.fa-dashboard.fa-fw
                  Dashboard
              %li
                %a{:href => "#"}
                  %i.fa.fa-bar-chart-o.fa-fw
                  Charts
                  %span.fa.arrow
                %ul.nav.nav-second-level.collapse
                  %li
                    %a{:href => "flot.html"} Flot Charts
                  %li
                    %a{:href => "morris.html"} Morris.js Charts
              %li
                %a{:href => "tables.html"}
                  %i.fa.fa-table.fa-fw
                  Tables
              %li
                %a{:href => "forms.html"}
                  %i.fa.fa-th.fa-fw
                  Friends List
      - if user_signed_in?
        = friends_for_user
      .container
        - {'alert-success' => notice, 'alert-danger' => alert}.each do |k,v|
          - if v
            = render 'layouts/flash', klass: k, notice: v
        = yield

app/views/tweets/_form.html.haml
- tweet ||= Tweet.new
.row
  = form_for [current_user, tweet], class: 'form-group' do |f|
    .row
      .form-group.col-sm-6.col-sm-offset-3
        = f.text_area :content, class: 'form-control', placeholder: 'Tweet some news...'
    .row.col-sm-2.col-sm-offset-5.text-center
      .form-group
        = f.submit 'Tweet', class: 'btn btn-success'

app/views/tweets/edit.html.haml
= render 'form', tweet: @tweet

app/views/tweets/index.html.haml
= render 'form'
.row
  - @tweets.each do |x|
    .col-sm-6.col-sm-offset-3
      .panel.panel-default
        .panel-heading
          = x.user.login
          posted
          = time_ago_in_words(x.created_at)
          ago
        .panel-body
          = x.content
        .panel-footer
          = form_tag(like_user_tweet_path(x.user, x), method: 'put', remote: true, class: 'form-inline tweet-like') do
            %button.btn.btn-danger.btn-circle
              %i.fa.fa-heart
              %span.likes-count= x.get_likes.count
          = link_to 'Edit', edit_user_tweet_path(current_user, x), class: "btn btn-xs btn-primary"
          = link_to 'Destroy', user_tweet_path(current_user, x), class: "btn btn-xs btn-warning", data: {:confirm => 'Are you sure?'}, :method => :delete